name: Static Scans

on:
  #push: # not on push for the training (just manual)
  workflow_dispatch: # to allow running manually

permissions:
  contents: read

jobs:
  sast-scans:
    name: SAST Scans
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Sources
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: "temurin"

      - name: Setup Maven Dependency Cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install

      # ======================================================

      - name: Generate CycloneDX SBOM
        run: mvn org.cyclonedx:cyclonedx-maven-plugin:2.7.9:makeAggregateBom # outputs to target/bom.json and/or bom.xml

      - name: Upload SBOM as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-cyclonedx.json
          path: target/bom.json

      # ======================================================

      - name: Grype Dependency Scanner (Report)
        id: scan
        uses: anchore/scan-action@be7a22da4f22dde446c4c4c099887ff5b256526c
        with:
          path: "."
          fail-build: false # to always generate the report, then again a scan that might fail

      - name: Upload Grype SARIF Results
        uses: actions/upload-artifact@v4
        with: # Yep, you can open this file in your IDE: Just drag and drop it into IntelliJ IDEA or Visual Studio Code
          name: grype-scan-results.sarif
          path: ${{ steps.scan.outputs.sarif }}

      # ======================================================

      - name: Download SpotBugs CLI + FindSecBugs Rule Pack
        run: |
          # Download SpotBugs with SHA256 verification
          wget -O spotbugs.tgz https://github.com/spotbugs/spotbugs/releases/download/4.9.3/spotbugs-4.9.3.tgz
          echo "d464d56050cf1dbda032e9482e1188f7cd7b7646eaff79c2e6cbe4d6822f4d9f  spotbugs.tgz" | sha256sum -c -
          tar -xzf spotbugs.tgz
          mv spotbugs-*/ spotbugs/

          # Download FindSecBugs with SHA256 verification
          wget -O findsecbugs.jar https://search.maven.org/remotecontent?filepath=com/h3xstream/findsecbugs/findsecbugs-plugin/1.12.0/findsecbugs-plugin-1.12.0.jar
          echo "97604c6be648184fdafaf2df5f4bdbc8ec5c7468677847a6c42f4a09d81610ba  findsecbugs.jar" | sha256sum -c -
          mv findsecbugs.jar spotbugs/plugin/.

      - name: Run SpotBugs CLI (SARIF)
        run: |
          spotbugs/bin/spotbugs -sarif:/tmp/raw-spotbugs-output.txt -effort:max -low -auxclasspath lib:target/classes target/classes > /tmp/raw-spotbugs-output.txt
          grep -A100000 '{"version"' /tmp/raw-spotbugs-output.txt > /tmp/spotbugs-results.sarif

      - name: Upload SpotBugs SARIF Results
        uses: actions/upload-artifact@v4
        with: # Yep, you can open this file in your IDE: Just drag and drop it into IntelliJ IDEA or Visual Studio Code
          name: spotbugs-scan-results.sarif
          path: /tmp/spotbugs-results.sarif
